### ISSUE TITLE
Optional timeout for range and manual endpoints

### ISSUE THREAD

**Issue by WnP** [prsolucoes/gohc#6]
Ranges are used for timeout for ping healthcheck, I guess it could be nice to have "ranges" available only for "range" healthcheck type and implement an optional timeout for all types based on the "ranges" logic for "ping" healthcheck.

Maybe this imply to create an other status.

Let me know your through.

**Comment by paulocoutinhox** [comment]
Hi,

I don't understand your suggestion. Can you explain more?

Thanks.

**Comment by WnP** [comment]
Ping health check types use ranges to define timeouts, see on configuration:

https://github.com/prsolucoes/gohc/blob/ce3847cbec30ba50150283c097aa2c0df150f1e8/extras/sample/config.json#L7-L14

And how it's implemented:

https://github.com/prsolucoes/gohc/blob/ce3847cbec30ba50150283c097aa2c0df150f1e8/models/domain/healthcheck.go#L33-L44

`This.Ping` is here to retrive a timeout, see how it's computed:

https://github.com/prsolucoes/gohc/blob/ce3847cbec30ba50150283c097aa2c0df150f1e8/models/domain/healthcheck.go#L100-L105

The suggestion is to make this kind of timeout available for "manual" and "range" health checks, which means for example that a given "manual" health check should update it's value every x ms to be considered safe.

With this feature a "manual" health check can have 4 different states:

- Success: checker respond `success` in time
- Warning: checker respond `warning` in time
- Error: checker respond `error` in time
- timeout: check doesn't respond in required time

This timeout metric allow users to know if checker are alive or not.

Maybe a range is not appropriate for that kind of purpose and just a timeout setting expressed in ms could be enough.

**Comment by paulocoutinhox** [comment]
I think that i understand. But let's talk.

Ping healthcheck have the feature that you want, because is natural of this type.

But "manual" need be manually defined. Manual is defining that the rule is controlled by the caller and not by the server.

And "range" need be defined by the caller too (its value). And based on value sent the server update its state.

You are saying that we need a "timeout" property (one for manual and other for range) that the server will check, and if timeout, set "manual" or "range" with state = error? So the caller always need call the gohc in the timeout time, if not, state = error.

Is this?

**Comment by WnP** [comment]
Exactly, that's what I mean.

By the way I think settings state to error is not the better choice, IMHO a explicite "timeout" state would be preferable.

**Comment by paulocoutinhox** [comment]
Hi,

I made the update to include this function. Now it has timeout support. Web interface was updated and its dependencies.

Can you check?

I will create a new release tag in 1 week.

Thanks.

**Comment by paulocoutinhox** [comment]
Release created:
https://github.com/prsolucoes/gohc/releases/tag/1.1.0

Thanks.
